# Generated by Django 5.2.10 on 2026-01-07 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="creada",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="empresa",
            name="ruc",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
