# Generated by Django 5.2.10 on 2026-01-07 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_empresa_creada_alter_empresa_ruc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="ruc",
        ),
        migrations.AddField(
            model_name="empresa",
            name="mongo_db",
            field=models.CharField(default="cerocodigo_modelos", max_length=100),
        ),
        migrations.AddField(
            model_name="empresa",
            name="mongo_uri",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="URI de MongoDB para los modelos declarativos",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuarioempresa",
            name="activa",
            field=models.BooleanField(default=True),
        ),
    ]
