# Generated by Django 5.2.10 on 2026-01-10 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_empresa_ruc_empresa_mongo_db_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="sql_clave",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="URI de sql para los datos del empresa",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresa",
            name="sql_db",
            field=models.CharField(default="base de datos", max_length=100),
        ),
        migrations.AddField(
            model_name="empresa",
            name="sql_url",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="URI de sql para los datos del empresa",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresa",
            name="sql_user",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="URI de sql para los datos del empresa",
                max_length=500,
            ),
            preserve_default=False,
        ),
    ]
